site_name: Kihana's Blog
site_description: Kihana的个人博客
site_author: Kihana
site_url: https://www.kihana.fun/
repo_url: https://github.com/kihana2077/KihanaPage
repo_name: KihanaPage

theme:
  name: material
  custom_dir: overrides  
  language: zh
  font: Noto Sans Simplified Chinese
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 跟随系统
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: 亮色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 暗色模式
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - toc.follow
    - tags


plugins:
  - search
  - statistics
  - blog: 
      blog_dir: blog/2025/
      blog_toc: true
  - blogging:
      locale: zh
      dirs:
        - blog
      features:
        tags: {}
      theme:
        name: card
        time_format: '%Y-%m-%d %H:%M:%S'
        # meta_time_format: '%Y-%m-%d %H:%M:%S'
  - tags
  - document-dates:
      position: top            # 显示位置：top（标题后） bottom（文档末尾）
      type: datetime               # 时间类型：date datetime timeago，默认：date
      exclude:                 # 排除文件列表
        - temp.md              # 排除指定文件
        - drafts/*             # 排除 drafts 目录下所有文件，包括子目录
      locale: zh               # 本地化语言：en zh zh_TW es fr de ar ja ko ru，默认：en
      date_format: '%Y-%m-%d'  # 日期格式化字符串，例如：%Y年%m月%d日、%b %d, %Y
      time_format: '%H:%M'  # 时间格式化字符串（仅在 type=datetime 时有效）
      show_author: true        # 是否显示作者信息，默认：true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true

# nav: 
#   - 首页: index.md
#   - 留言板: contact.md
#   - 友链: friend.md
#   - 标签: tags.md
#   - Blog: 
#       - 正则表达式 语法: 正则.md
#       - Markdown语法: 使用Markdown.md
#       - Admonition扩展语法: material.md
#       - Github Pages文档自动化部署: first.md
#       - 我的第一篇博客: 我的第一篇博客.md


markdown_extensions:
      - abbr
      - attr_list
      - admonition
      - def_list
      - footnotes
      - md_in_html
      - meta # 支持Markdown文件上方自定义标题标签等
      - pymdownx.caret
      - pymdownx.betterem
      - pymdownx.critic
      - pymdownx.details
      - pymdownx.inlinehilite
      - pymdownx.keys
      - pymdownx.mark
      - pymdownx.snippets
      - pymdownx.smartsymbols
      - pymdownx.tilde
      - pymdownx.superfences:
          custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
      - pymdownx.arithmatex:  # latex支持
          generic: true
      - toc:
          permalink: true # 固定标题位置为当前位置
          toc_depth: 3
      - pymdownx.highlight: # 代码块高亮
          anchor_linenums: true
          linenums: true # 显示行号
          auto_title: true # 显示编程语言名称
      - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
      - pymdownx.tabbed:
          alternate_style: true
      - pymdownx.tasklist:
          custom_checkbox: true
      - markdown.extensions.toc:
          slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
          permalink: "\ue157"

extra_css:
  - stylesheets/extra.css
  - stylesheets/custom.css
  - stylesheets/code.css
# extra_javascript:
#   - javascripts/theme_switcher.js
# hooks:
#   - overrides/hooks/reading_time.py


copyright: Copyright © 2025 Kihana <a href="https://icp.gov.moe/?keyword=20250772" target="_blank">萌ICP备20250772号</a>  


extra: 
  # alternate:
  #       - name: English
  #         link: https://kihana-fun.translate.goog/?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp 
  #         lang: en
  #       - name: 繁体中文
  #         link: https://kihana-fun.translate.goog/?_x_tr_sl=zh-CN&_x_tr_tl=zh-TW&_x_tr_hl=zh-CN&_x_tr_pto=wapp
  #         lang: zh-TW
  generator: true
